import re
import math
from typing import Dict, Any, List

# Characteristic LLM connective & hedging clichés frequently generated by models like ChatGPT / Claude / Gemini
AI_CLICHE_PATTERNS = [
    r"\bit is (important|crucial|essential|worth noting) to (remember|note|recognize|understand)\b",
    r"\bfurthermore\b",
    r"\bmoreover\b",
    r"\bin conclusion\b",
    r"\bdelving into\b",
    r"\ba testament to\b",
    r"\brich tapestry\b",
    r"\bmultifaceted\b",
    r"\bparamount\b",
    r"\bin summary\b",
    r"\bplays a (vital|crucial|pivotal) role in\b",
    r"\bnavigating the complexities of\b",
    r"\bunlocking the potential of\b",
    r"\bbeacon of (hope|innovation|progress)\b",
    r"\btransformative (impact|journey|power)\b",
    r"\bharnessing the power of\b"
]

def calculate_entropy(text: str) -> float:
    """Calculate Shannon entropy over character distributions."""
    if not text:
        return 0.0
    text_lower = text.lower()
    freq = {}
    for char in text_lower:
        freq[char] = freq.get(char, 0) + 1
    
    entropy = 0.0
    length = len(text_lower)
    for count in freq.values():
        p = count / length
        entropy -= p * math.log2(p)
    return round(entropy, 2)

def calculate_burstiness(sentences: List[str]) -> Dict[str, Any]:
    """
    Calculate burstiness (variance of sentence lengths).
    Human writing has high burstiness (mix of very short and long sentences).
    AI writing has low burstiness (uniform, measured sentence lengths).
    """
    if len(sentences) <= 1:
        return {"burstiness_score": 50.0, "std_dev": 0.0, "variance": 0.0, "mean_length": len(sentences[0].split()) if sentences else 0}

    lengths = [len(s.split()) for s in sentences if s.strip()]
    if not lengths:
        return {"burstiness_score": 50.0, "std_dev": 0.0, "variance": 0.0, "mean_length": 0}

    mean_len = sum(lengths) / len(lengths)
    variance = sum((x - mean_len) ** 2 for x in lengths) / len(lengths)
    std_dev = math.sqrt(variance)

    # Coefficient of variation (CV = std_dev / mean)
    cv = (std_dev / mean_len) if mean_len > 0 else 0
    # Scaled burstiness score (0 to 100). Higher = more human-like variance
    burstiness_score = min(100.0, max(0.0, cv * 70.0))

    return {
        "burstiness_score": round(burstiness_score, 1),
        "std_dev": round(std_dev, 2),
        "mean_length": round(mean_len, 1),
        "sentence_count": len(lengths)
    }

def analyze_text_forensics(text: str) -> Dict[str, Any]:
    """
    Analyzes input text for statistical stylometry, entropy, burstiness,
    and synthetic LLM structural clichés.
    Returns composite AI vs Human authorship probability.
    """
    clean_text = (text or "").strip()
    if not clean_text:
        return {
            "ai_probability": 0.0,
            "human_probability": 100.0,
            "verdict_label": "INSUFFICIENT TEXT",
            "perplexity_index": 0.0,
            "burstiness_score": 0.0,
            "entropy_score": 0.0,
            "flagged_phrases": [],
            "analysis_summary": "No text provided for forensic evaluation."
        }

    # 1. Sentence splitting
    sentences = [s.strip() for s in re.split(r'[.!?]+', clean_text) if len(s.strip()) > 3]
    words = re.findall(r'\b\w+\b', clean_text.lower())
    total_words = len(words)

    # 2. Burstiness calculation
    burst_data = calculate_burstiness(sentences)
    burst_score = burst_data["burstiness_score"]

    # 3. Entropy & Type-Token Ratio (TTR)
    entropy = calculate_entropy(clean_text)
    unique_words = len(set(words))
    ttr = (unique_words / total_words) if total_words > 0 else 1.0

    # 4. Pattern matching for synthetic LLM clichés
    flagged_phrases = []
    cliche_hits = 0
    for pattern in AI_CLICHE_PATTERNS:
        matches = list(re.finditer(pattern, clean_text, re.IGNORECASE))
        for m in matches:
            cliche_hits += 1
            flagged_phrases.append({
                "phrase": m.group(0),
                "start": m.start(),
                "end": m.end(),
                "category": "Synthetic Connective / LLM Cliché"
            })

    # 5. Composite AI Probability Heuristic
    # Base AI weight from low burstiness
    ai_burst_weight = max(0.0, (65.0 - burst_score) * 0.7)
    
    # Cliche density weight (hits per 100 words)
    cliche_density = (cliche_hits / max(1, total_words / 100)) * 22.0
    
    # Uniformity penalty
    uniformity_penalty = 15.0 if burst_data["std_dev"] < 3.5 and len(sentences) >= 3 else 0.0

    raw_ai_prob = min(98.0, max(4.0, 15.0 + ai_burst_weight + cliche_density + uniformity_penalty))
    
    # Estimate Perplexity (inverse proxy from entropy and burstiness)
    perplexity = round(max(10.0, min(140.0, 30.0 + (burst_score * 0.8) + (entropy * 8.0))), 1)

    ai_prob = round(raw_ai_prob, 1)
    human_prob = round(100.0 - ai_prob, 1)

    if ai_prob >= 70.0:
        verdict = "LIKELY AI-GENERATED (SYNTHETIC)"
        risk_color = "#ef4444"
    elif ai_prob >= 40.0:
        verdict = "HYBRID / MIXED AUTHORSHIP"
        risk_color = "#f59e0b"
    else:
        verdict = "LIKELY HUMAN-AUTHORED"
        risk_color = "#10b981"

    summary = (
        f"Analyzed {total_words} words across {len(sentences)} sentences. "
        f"Sentence burstiness index is {burst_score}/100 with {cliche_hits} synthetic stylistic markers detected. "
        f"Overall assessment indicates {verdict}."
    )

    return {
        "ai_probability": ai_prob,
        "human_probability": human_prob,
        "verdict_label": verdict,
        "risk_color": risk_color,
        "perplexity_index": perplexity,
        "burstiness_score": burst_score,
        "entropy_score": entropy,
        "type_token_ratio": round(ttr, 3),
        "total_words": total_words,
        "total_sentences": len(sentences),
        "flagged_phrases": flagged_phrases[:8],
        "analysis_summary": summary
    }
